### ISSUE TITLE
Impossibile caricare immagine in SchoolSharing

### ISSUE THREAD

**Issue by MrIndeciso** [toto04/nfapp#10]
Nel form per aggiungere una nota allo SchoolSharing non funziona il tasto "Aggiungi Immagine", non fa assolutamente nulla.
Ho provato a concedergli manualmente il permesso di usare la fotocamera ma il risultato non cambia.
Also una piccola typo qui: 
![photo_2020-03-25_00-19-09](https://user-images.githubusercontent.com/6383492/77485801-64fbdc80-6e2e-11ea-9706-73856af734a3.jpg)

**Comment by toto04** [comment]
Ok a quanto pare ho messo il permesso sbagliato in app.json, adesso ho testato e dovrebbe funzionare
