### ISSUE TITLE
L'APK per Android richiede troppi permessi

### ISSUE THREAD

**Issue by MrIndeciso** [toto04/nfapp#7]
![photo6019619952560025697](https://user-images.githubusercontent.com/6383492/77055186-c22c0400-69d0-11ea-9df4-580900664372.jpg)
![photo6019619952560025698](https://user-images.githubusercontent.com/6383492/77055200-c6f0b800-69d0-11ea-8985-77d3fae76269.jpg)

Il problema è nel file di configurazione di Expo, cioè app,json

Questo è ciò che c'è scritto nella documentazione di Expo a questa pagina: https://docs.expo.io/versions/latest/workflow/configuration/

>  /*   List of additional permissions the standalone app will request upon installation,
      along with the minimum necessary for an Expo app to function.
      To use ALL permissions supported by Expo, do not specify the "permissions" key.
      To use ONLY the following minimum necessary permissions and none of the extras supported
      by Expo, set "permissions" to []. The minimum necessary permissions do not require a
      Privacy Policy when uploading to Google Play Store and are:
      • receive data from Internet
      • view network connections
      • full network access
      • change your audio settings
      • draw over other apps
      • prevent device from sleeping
      To use the minimum necessary permissions ALONG with certain additional permissions,
      specify those extras in "permissions", e.g.
      ["CAMERA", "RECORD_AUDIO"]
      ExpoKit: to change the permissions your app requests, you'll need to edit
      AndroidManifest.xml manually. To prevent your app from requesting one of the
      permissions listed below, you'll need to explicitly add it to `AndroidManifest.xml`
      along with a `tools:node="remove"` tag.
    */

Nel vostro app.json non c'è la key "permissions" e quindi richiede tutti i permessi. Questo è un problema, perchè se Google dovesse decidere di cambiare qualcosa, come fa più o meno 7 volte al giorno, l'app non sarebbe più installabile.
Inoltre avete il target su API 28, ma c'è già la 29 e manca qualche mese alla 30 (ci sono già i buildtools 30-rc01). Non dovrebbero esserci problemi ad aggiornare perchè non usate roba che potrebbe essere rotta dallo Scoped Storage.

Allego anche lo screenshot di un AndroidManifest.xml normale e il vostro decompilato.
![Capture2](https://user-images.githubusercontent.com/6383492/77055807-d3c1db80-69d1-11ea-9091-42e65a8bbb59.PNG)
![Capture](https://user-images.githubusercontent.com/6383492/77055810-d58b9f00-69d1-11ea-8c0a-9d9505525344.PNG)

**Comment by J3is** [comment]
Non credo si tratti soltanto di una questione di futuri cambi di Google e di possibile "non installabilità" dell'app, ma anche di una questione legale.
Orio mi ha inoltrato l'audio in cui si diceva che questi sono i permessi minimi richiesti da Google per le app, ma mi risulta che siano molto meno (quelli scritti sopra e nella documentazione di Expo), anche perché logicamente non credo che, ad esempio, "attività fisica" sia necessario per tutte le app.
Sarebbe meglio risolvere (alla fine si tratta di specificare una chiave in un JSON) per evitare possibili problemi futuri, come anche diffidenza da parte di chi fa caso a ciò a cui le proprie app hanno accesso, e che potrebbe quindi preoccuparsi.
![Screenshot_20200317-194213](https://user-images.githubusercontent.com/13227393/77096593-d5aa8f80-6a0f-11ea-8a43-ba86b24c2c5a.jpg)

**Comment by toto04** [comment]
Sì grazie ragazzi.
Non sapevo che per il bundle di Android si sarebbe comportato in questo modo, e dato che iOS non sembra avere lo stesso problema non me ne sarei mai accorto.
Ed ecco a cosa serve il beta testing ahah, fixerò il prima possibile

**Comment by toto04** [comment]
Ok dovrebbe essere risolto nel commit 9516127b582467cf88a24cec2c9f0c18ce9a34b4
Ho già ricompilato e ricaricato l'app su playstore, controllate che sia tutto sistemato e in caso vi invito a riaprire una issue.

Una nota sulla versione dell'API, dipende dalla versione dell'expo SDK, sto usando la versione 35 che appunto ha come target l'API 28, che era l'ultima versione quando ho incominciato a costruire l'app. Possiamo in un futuro passare expo SDK v36 ma il processo non è esattamente immediato e non lo considero una priorità in questo momento.
