### ISSUE TITLE
Le classi non dovrebbero essere compilate nell'applicazione

### ISSUE THREAD

**Issue by MrIndeciso** [toto04/nfapp#8]
Al momento tieni le classi codificate nel file Classes.ts
Il problema è che, così facendo, per modificare le classi della scuola è necessario ricompilare l'applicazione.
Sarebbe meglio scaricare le classi dinamicamente dal server, in modo che negli anni successivi sia più semplice aggiornare l'applicazione.

Se ti interessa ho scritto un parser in Python, che puoi benissimo far girare su Heroku, che estrae orario, classi, materie e insegnanti dal file in PDF dell'orario e restituisce il risultato in alcuni file JSON.

**Comment by toto04** [comment]
Il fatto è che essendo l'app pubblicata via expo non va ricompilata l'intera applicazione e ripubblicata sugli store, expo ricrea da solo il bundle js che verrà scaricato automaticamente sui dispositivi su cui è installata l'app all'avvio successivo. Di fatto è lo stesso risultato che otterresti se tentassi di controllare se la struttura delle classi è cambiata a ogni avvio fetchandola ad ogni avvio.
Avrebbe comunque senso se le modifiche non fossero così sporadiche, direi che una volta all'anno ci si può permettere di usare 2 minuti per ripubblicare il bundle js.

Poi il parser per il momento non dovrebbe nemmeno servire, in teoria le materie non dovrebbero quasi mai cambiare all'interno dello stesso indirizzo, e i rappresentanti non hanno richiesto alcuna funzione che richieda orari o insegnanti, ma se in caso dovessero decidere di fare qualcosa di questo genere ci penseremo
