### ISSUE TITLE
Icona dinamica e titoli delle sezioni

### ISSUE THREAD

**Issue by J3is** [toto04/nfapp#9]
Si tratta di piccolezze estetiche, ma io con la grafica sono un bastardo e quindi le faccio presente lo stesso.

L'icona dell'app è statica; da Android 8 in poi (e questo vale per AOSP, le interfacce custom dei produttori probabilmente lo fanno da prima), il launcher modifica dinamicamente la forma delle icone, che possono diventare tonde, quadrate o a goccia. Se l'icona supporta questa funzionalità, può adattarsi alla nuova forma, mentre se è statica, appare semplicemente come un piccolo quadrato all'interno della forma. Ovviamente ciò non comporta nulla per il funzionamento dell'app, ma stona un po' con il resto delle icone.
Un esempio a confronto con Instagram, tonda e quadrata:

![Screenshot_20200324-205929](https://user-images.githubusercontent.com/13227393/77472095-b5197580-6e13-11ea-9e50-b76c26318487.jpg) ![Screenshot_20200324-205929 copia](https://user-images.githubusercontent.com/13227393/77472101-b64aa280-6e13-11ea-9fba-e3d7dccd3ca9.jpg)
![Screenshot_20200324-205402](https://user-images.githubusercontent.com/13227393/77472096-b5b20c00-6e13-11ea-8515-7277c53adf3c.jpg) ![Screenshot_20200324-205402 copia](https://user-images.githubusercontent.com/13227393/77472098-b5b20c00-6e13-11ea-9348-dbd64724a0dd.jpg)
(non so ritagliare le cose in modo decente)

Per quanto riguarda i titoli, invece, ho notato che alcuni hanno l'iniziale maiuscola ed altri minuscola, altra piccolezza ma che inficia la consistenza del design.

**Comment by toto04** [comment]
Oof chiaro, ne parlerò con l'erica che sta facendo la grafica così sistemo
e dannazione credevo di averli messi tutti minuscoli i titoli argh

**Comment by J3is** [comment]
I titoli dei diversi sottomenu sono tutti in minuscolo, il problema è che le materie, così come i titoli delle sezioni, non lo sono e quindi si crea una certa incoerenza nel design.
Personalmente, i titoli tutti in minuscolo triggerano il mio OCD e riportano alla mente orride memorie di Windows Phone, però ovviamente non sono qui per decidere come dev'essere fatto il tutto.

**Comment by toto04** [comment]
rip per il tuo OCD ma come gusto personale preferisco tutto minuscolo ahah (forse non avendo mai usato windows phone), fixato con la soluzione più ignorante del mondo.
L'icona adattiva è stata implementata e ho anche aggiunto una versione rounded per versioni di android che non la supportano così almeno non è un quadrato orribile.
